Repository rapltech/moodle-mod_zoom, pull requests merged in 2021-07, with the labels that each got.

#28 FIX: Append access token for download
  classes/task/insert_recordings.php
  classes/webservice.php
  cli/update_meeting_recordings.php
Labels: enhancement

#27 FIX: Array elements should be accessed using []
  classes/task/insert_recordings.php
  cli/update_meeting_recordings.php
Labels: best practice

#29 Add/zoom user registrants
  classes/task/add_meeting_registrant.php
  classes/task/clear_registrant.php
  classes/webservice.php
  db/tasks.php
  db/upgrade.php
  lang/en/zoom.php
  lib.php
  loadmeeting.php
  mod_form.php
  settings.php
  version.php
Labels: enhancement

#34 change sql query to register every role user enrolled into course
  loadmeeting.php
Labels: bug

#35 Add/admin to register without enrollment
  helperfunctions.php
  loadmeeting.php
Labels: enhancement
